### ISSUE TITLE
Mini-BUG in der Domumentensuchfunktion

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#134]
Wenn man in der Dokumentensuche (da wo dann die Ergebnisse grün werden) nur einen Buchstaben eingibt (in meinem Fall ein großes E), dann läßt sich dieser Buchstabe nicht mit dem X-Button rechts löschen. Man muss reinklicken ins Fenster und ihn mit Del weglöschen. Minibug, wie gesagt.

**Comment by j-dimension** [comment]
Vielen Dank - ist behoben und wird mit 1.9.1 geliefert.
