### ISSUE TITLE
Festpinnen von Dokumenten auf Position

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#136]
Ich wünsche mir im Dokumentenordner eine "Pin"-Funktion, damit ich die Dokumente z.B. ganz oben halten kann (z.B. Zeiterfassungsformular oder Kostenblatt"). Bei größeren Dokumentenmengen wärs hilfreich. MFG

**Comment by j-dimension** [comment]
Sinnvoll! Wird zusammen mit https://github.com/jlawyerorg/j-lawyer-client/issues/86 erledigt.

**Comment by j-dimension** [comment]
Wurde mit #161 umgesetzt und mit Version 1.9.1 geliefert.
