### ISSUE TITLE
Refresh bei Tags

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#146]
Bei Erstellung eines neuen Tags erscheint dieser erst, wenn man aus dem Client aussteigt und wieder einsteigt, bzw. zumindest die Akte schließt und wieder öffnet, Das verleidet einem die Nutzung der Tags. To do - Refresh der Tagliste im Moment der Tagerstellung, damit dieser sofort zur Verfügung steht.

**Comment by j-dimension** [comment]
altes Verhalten: zyklische Prüfung aller 60s
neues Verhalten: sofortige Aktualisierung - Client muss nicht neu gestartet werden. Offene Akten werden aber nicht aktualisiert, d.h. ggf. Akte neu öffnen.
