### ISSUE TITLE
Dokumentenmonitor

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#148]
Wenn man einen Client (evt. von mehreren offenen) schließen will, zeigt er im Dokumentenmonitor die offenen Dokumente an. Es wäre hilfreich, wenn man auf eines (das man noch benötigt) Klicken kann, dann im offenen Dokument landet, dieses speichert und schließt und zurück im Dokumentmonitor ist. Hilfreich bei vielen offenen Dokumenten.

**Comment by j-dimension** [comment]
Es gibt keinen Weg der auf Windows, Linux, macOS gleichermaßen funktioniert.
