### ISSUE TITLE
Zugriff auf Management-Konsole (Box)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#152]
Ich wollte das update für die Konsole starten auf 1.2, komme aber mit den Zugangsdaten nicht auf die Konsole (Zugangsdaten aus Identity Card)... :-(

**Comment by j-dimension** [comment]
Login nicht mit Betriebssystemnutzer, sondern Nutzer der Kanzleisoftware gemacht? In die Managementkonsole können sich alle Nutzer einloggen, die in der Nutzerverwaltung administrative Rechte haben.

**Comment by Mucki526** [comment]
Oh, danke! Das Problem saß auf dem Schlauch -  50 cm hinter der Tastatur... :-). Update erledigt.
