### ISSUE TITLE
Vorlage für Zeiterfassung aufnehmen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-client#156]
[Akte-Zeiterfassung.ods.zip](https://github.com/jlawyerorg/j-lawyer-client/files/2134782/Akte-Zeiterfassung.ods.zip)

**Comment by Mucki526** [comment]
Ich habe da eine Excel-Vorlage / Libreoffice Calc und übernehme diese auch über die Zwischenablage in die Kostennote. Da wäre ein Button "Zeiterfassung" neben "Notiz" im Dokumentenordner von J-Lawyer hilfreich, der automatisch die Vorlage Zeiterfassung öffnet.

**Comment by j-dimension** [comment]
Das mit dem Zeiterfassungsknopf überlege ich mir. Eventuell kann man das allgemeiner gestalten (bspw. Dokumente als "Favoriten" markieren und diese dann über den Aktenkopf schnell zugreifbar haben).

**Comment by j-dimension** [comment]
Split in zwei Tickets, dieses hier und #161

**Comment by j-dimension** [comment]
Vorlage als "mneumann-zeiterfassung.ods" in den Installer aufgenommen
