### ISSUE TITLE
Adresseingaben

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#165]
Ich hätte gerne mehr Flexibilität bei der Adresseingabe. Eine Weitere Zeile für einen Absenderzusatz Im Moment quetsche ich z.B. den Zusatz Amtsgericht -Familiengericht - in die Zeile Vornamen... ebenso c/o Zusätze.... Postfachadressen dto.

**Comment by j-dimension** [comment]
Das ist über Tickets #82 und #98 bereits eingeplant. Ich habe Dich dort als Beobachter eingetragen und schliesse dieses hier als Duplikat.
