### ISSUE TITLE
Vorlage kopieren

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#173]
Wenn man eine Vorlage kopieren will und sie auswählt und dann auf kopieren geht. wird im sich öffnenden Fenster als Kopiervorlage nicht diese Datei sondern .directory angezeigt. Man muss erst nochmal die gehighlightete Datei von Hand auswählen. Sinnvoller wäre als Standard die vorher markierte Datei. Dann ist es auch schlüssig mit anderen Kopiervorgängen in J-lawyer

**Comment by j-dimension** [comment]
Das ist bereits umgesetzt und wird mit der 1.9.1 geliefert.
