### ISSUE TITLE
Scanergebnis

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-client#189]
Mandanten konnten jetzt zweimal ein PDF nicht aufmachen, das korrekt bei mir gespeichert ist. Ich bin jetzt drauf gekommen, dass es sehr große PDF mit vielen Seiten betrifft. Der Scan wird über den Scanner durchs Netzwerk geschickt. Die Datei wird im Scanordner angelegt, aber man erkennt im Scannordner offensichtlich nicht, dass zwar der Name vollständig da ist, aber die Datei noch durch die Leitung rieselt und noch nicht vollständig ist.  Idee - ein paar Laufpunkte hinter der Datei im scanordner, bis diese vollständig abgespeichert ist...

**Comment by j-dimension** [comment]
Erledigt.
