### ISSUE TITLE
Beteiligtenansicht: UI-Verbesserungen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-client#206]
Werden die Details eines Beteiligten expandiert, bekommen alle anderen Beteiligten den gleichen Platz - Eigenheit von Gridlayout. Umstellung auf Gridbaglayout wäre möglich, oder ganz anders lösen via Master/Detail-Ansicht.

**Comment by j-dimension** [comment]
@RasimT

**Comment by j-dimension** [comment]
BoxLayout!  --> noch in 1.9.1 gelöst

**Comment by RasimT** [comment]
Einfach Genial!
Wie war Zypern!
Hoffe Sie konnten Kraft tanken!
LG Raim Tosun

Von: Jens Kutschke [mailto:notifications@github.com]
Gesendet: Freitag, 19. Oktober 2018 22:47
An: jlawyerorg/j-lawyer-client <j-lawyer-client@noreply.github.com>
Cc: Rechtsanwalt Tosun <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-client] Beteiligtenansicht: UI-Verbesserungen (#206)


BoxLayout! --> noch in 1.9.1 gelöst
